Add note: bootstrap.js function is required
When updating strapi to beta16 following migration doc its mentioned that cb() must be removed. Alternatives are provided, however it isn't mentioned that "any function" is required. This doc provides a workaround until a user provided bootstrap function is no longer required ... maybe?

Without bootstrap.js exporting a valid function you get this error:

error TypeError: fn is not a function
    at execBootstrap (.../src/node_modules/strapi/lib/Strapi.js:381:15)
    at Strapi.runBootstrapFunctions (../src/node_modules/strapi/lib/Strapi.js:399:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)